### ISSUE TITLE
retrieval 文件夹下 run.sh 脚本文件内容问题

### ISSUE THREAD

**Issue by self-discipline-zhu** [h-peng17/MMET#2]
### 文件链接：
[run.sh](https://github.com/h-peng17/MMET/blob/main/retrieval/run.sh)

### 问题描述：
1. `run.sh` 脚本分支处理中出现 `recall.py` 文件，而在项目中并没有找到相关文件。
2. 同文件夹下的 `retrieve.py` 文件中引用文件名为 `recall_***`，而当前文件夹下只存在 `retrieve_***`  文件
```
from recall_image import ImageRecallModel, ImageEncoderModel, compute_multi_image_rep
from recall_text import TextRecallModel
from recall_utils import compute_topk, vote_topk, load_image_vector, load_once
```
### 猜想：
1. 由上述两个问题猜测是否是作者在上传时文件命名没有统一；如果不是，能否提供相应的文件？
2. `README` 文件中能否提供一些执行代码示例？如果可以的话那将非常感谢

**Comment by h-peng17** [comment]
你好，你提到的问题是文件命名不一致导致的，目前已经修改。（19301f5f0d49772ec02a9127e5c88d3a8b059cbe）
